In [6]:
!pip install stellargraph

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
# importing all necessary libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import os
import networkx as nx
import stellargraph as sg
from stellargraph import StellarGraph
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
#from node2vec import Node2Vec as n2v
sns.set()

%matplotlib inline

In [8]:
df = pd.read_csv('Student-Employability-Dataset.csv')
df.head()
# Dataset is now stored in a Pandas Dataframe

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating           CLASS  
0                     5                           5      Employable  
1                     3                           5      Employable  
2                     2                           5  LessEmployable  
3                     3                           5  LessEmployable  
4                     3                           5      Employable

In [9]:
df.shape

(2982, 9)

In [10]:
df['CLASS'].value_counts()

Employable        1729
LessEmployable    1253
Name: CLASS, dtype: int64

In [11]:
z = {'Employable' : 1, 'LessEmployable' : 0}
df['CLASS'] = df['CLASS'].map(z)
df.head()

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating  CLASS  
0                     5                           5      1  
1                     3                           5      1  
2                     2                           5      0  
3                     3                           5      0  
4                     3                           5      1

In [12]:
#node_Class
node_Class = df["CLASS"]

In [13]:
u3=df.drop(['CLASS'], axis=1)
u3.head()

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating  
0                     5                           5  
1                     3                           5  
2                     2                           5  
3                     3                           5  
4                     3                           5

### Distance calculation for creating adjacency matrix


In [14]:
from scipy.spatial.distance import cdist
s = cdist(u3, u3, 'cosine')
s

array([[0.00000000e+00, 1.18196406e-02, 3.89451766e-02, ...,
        5.70574961e-03, 1.75078592e-02, 1.18196406e-02],
       [1.18196406e-02, 0.00000000e+00, 1.07846501e-02, ...,
        6.69736532e-03, 3.57110435e-03, 7.69230769e-03],
       [3.89451766e-02, 1.07846501e-02, 0.00000000e+00, ...,
        2.63323597e-02, 1.15390226e-02, 2.00296533e-02],
       ...,
       [5.70574961e-03, 6.69736532e-03, 2.63323597e-02, ...,
        0.00000000e+00, 1.50356688e-02, 6.69736532e-03],
       [1.75078592e-02, 3.57110435e-03, 1.15390226e-02, ...,
        1.50356688e-02, 1.11022302e-16, 1.14792702e-02],
       [1.18196406e-02, 7.69230769e-03, 2.00296533e-02, ...,
        6.69736532e-03, 1.14792702e-02, 0.00000000e+00]])

In [15]:
X1=pd.DataFrame(s)
X1

0         1         2         3         4         5         6     \
0     0.000000  0.011820  0.038945  0.031784  0.015827  0.023852  0.023828   
1     0.011820  0.000000  0.010785  0.018050  0.006520  0.010005  0.017776   
2     0.038945  0.010785  0.000000  0.016536  0.011513  0.008478  0.038122   
3     0.031784  0.018050  0.016536  0.000000  0.011438  0.010986  0.043910   
4     0.015827  0.006520  0.011513  0.011438  0.000000  0.007125  0.027587   
...        ...       ...       ...       ...       ...       ...       ...   
2977  0.038945  0.010785  0.000000  0.016536  0.011513  0.008478  0.038122   
2978  0.005318  0.007692  0.029275  0.018050  0.014663  0.018689  0.026871   
2979  0.005706  0.006697  0.026332  0.030187  0.015583  0.013821  0.017178   
2980  0.017508  0.003571  0.011539  0.010289  0.003757  0.009008  0.018263   
2981  0.011820  0.007692  0.020030  0.018050  0.014663  0.010005  0.017776   

          7         8         9     ...      2972      2973      2974  \
0     0.036119  0.005732  0.010824  ...  0.055234  0.021551  0.015827   
1     0.017689  0.003403  0.011479  ...  0.039031  0.008924  0.006520   
2     0.009505  0.018376  0.021043  ...  0.021836  0.019694  0.011513   
3     0.031092  0.015332  0.020186  ...  0.030511  0.023098  0.021630   
4     0.021789  0.008436  0.012128  ...  0.034596  0.015815  0.008621   
...        ...       ...       ...  ...       ...       ...       ...   
2977  0.009505  0.018376  0.021043  ...  0.021836  0.019694  0.011513   
2978  0.034339  0.003403  0.011479  ...  0.048837  0.017695  0.014663   
2979  0.024151  0.004957  0.007793  ...  0.039112  0.020072  0.008125   
2980  0.024357  0.006251  0.016260  ...  0.042308  0.008163  0.012128   
2981  0.017689  0.003403  0.003571  ...  0.029225  0.017695  0.006520   

          2975      2976      2977      2978      2979          2980      2981  
0     0.022710  0.031191  0.038945  0.005318  0.005706  1.750786e-02  0.011820  
1     0.006520  0.018689  0.010785  0.007692  0.006697  3.571104e-03  0.007692  
2     0.011513  0.018915  0.000000  0.029275  0.026332  1.153902e-02  0.020030  
3     0.021630  0.043591  0.016536  0.018050  0.030187  1.028900e-02  0.018050  
4     0.017241  0.025511  0.011513  0.014663  0.015583  3.756706e-03  0.014663  
...        ...       ...       ...       ...       ...           ...       ...  
2977  0.011513  0.018915  0.000000  0.029275  0.026332  1.153902e-02  0.020030  
2978  0.014663  0.036057  0.029275  0.000000  0.006697  1.147927e-02  0.007692  
2979  0.008125  0.021774  0.026332  0.006697  0.000000  1.503567e-02  0.006697  
2980  0.012128  0.026863  0.011539  0.011479  0.015036  1.110223e-16  0.011479  
2981  0.006520  0.018689  0.020030  0.007692  0.006697  1.147927e-02  0.000000  

[2982 rows x 2982 columns]

In [16]:
# taking average of the hamming distance matrix
y = np.average(X1)
y

0.01856620671593297

In [17]:
adjmat_df=X1.copy()

In [18]:
# setting threshold value as mean of hamming matrix
adjmat_df[adjmat_df < y]=0
adjmat_df[adjmat_df >= y]=1

In [19]:
# adjacency matrix
adjmat_df

0     1     2     3     4     5     6     7     8     9     ...  2972  \
0      0.0   0.0   1.0   1.0   0.0   1.0   1.0   1.0   0.0   0.0  ...   1.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   1.0   
2      1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  ...   1.0   
3      1.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   1.0  ...   1.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0  ...   1.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2977   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  ...   1.0   
2978   0.0   0.0   1.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0  ...   1.0   
2979   0.0   0.0   1.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0  ...   1.0   
2980   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  ...   1.0   
2981   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   1.0   

      2973  2974  2975  2976  2977  2978  2979  2980  2981  
0      1.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
2      1.0   0.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0  
3      1.0   1.0   1.0   1.0   0.0   0.0   1.0   0.0   0.0  
4      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2977   1.0   0.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0  
2978   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  
2979   1.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  
2980   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
2981   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  

[2982 rows x 2982 columns]

In [20]:
G = nx.from_numpy_matrix(np.array(adjmat_df))
G

In [21]:
A=nx.to_numpy_matrix(G)
##Creating graph from adjacency matrix
H=nx.from_numpy_matrix(A)

### Construct a graph using stellargraph

In [22]:
from stellargraph import StellarGraph
graph1= StellarGraph.from_networkx(H)
print(graph1.info())

StellarGraph: Undirected multigraph
 Nodes: 2982, Edges: 1793526

 Node types:
  default: [2982]
    Features: none
    Edge types: default-default->default

 Edge types:
    default-default->default: [1793526]
        Weights: all 1 (default)
        Features: none


In [23]:
from stellargraph.data import BiasedRandomWalk
from stellargraph import StellarGraph
from stellargraph import datasets
from IPython.display import display, HTML

%matplotlib inline

In [24]:
rw = BiasedRandomWalk(graph1)

walks = rw.run(
    nodes=list(graph1.nodes()),  # root nodes
    length=100,  # maximum length of a random walk
    n=10,  # number of random walks per root node
    p=0.5,  # Defines (unormalised) probability, 1/p, of returning to source node
    q=2.0,  # Defines (unormalised) probability, 1/q, for moving away from source node
)
print("Number of random walks: {}".format(len(walks)))
from gensim.models import Word2Vec

str_walks = [[str(n) for n in walk] for walk in walks]
model = Word2Vec(str_walks, size=64, window=5, min_count=0, sg=1, workers=2, iter=1)

Number of random walks: 29820


In [25]:
# The embedding vectors can be retrieved from model.wv using the node ID as key.
model.wv["241"].shape

(64,)

In [26]:
# Retrieve node embeddings and corresponding subjects
node_ids = model.wv.index2word  # list of node IDs

node_embeddings = (
    model.wv.vectors
)  # numpy.ndarray of size number of nodes times embeddings dimensionality
node_targets = node_Class[[int(node_id) for node_id in node_ids]]

In [27]:
node_emb=pd.DataFrame(node_embeddings)


In [28]:
node_tar=pd.DataFrame(node_targets)
node_targets=node_tar.sort_index()

In [29]:
node_emb['Class']=node_targets

In [30]:
node_emb

0         1         2         3         4         5         6  \
0    -0.327528 -0.302725 -0.049724  0.052588 -0.141087  0.046769  0.097181   
1    -0.350010 -0.280961 -0.039398  0.035305 -0.119128  0.084197  0.078322   
2    -0.326544 -0.306474 -0.022861  0.058842 -0.142353  0.063663  0.081967   
3    -0.355287 -0.301026 -0.027737  0.049621 -0.131763  0.056909  0.071952   
4    -0.355417 -0.308985 -0.033043  0.051255 -0.130880  0.070281  0.089764   
...        ...       ...       ...       ...       ...       ...       ...   
2977 -0.389906 -0.231641  0.027144 -0.120040 -0.261588  0.017653 -0.006032   
2978 -0.381567 -0.231711  0.031284 -0.108395 -0.247845  0.014499 -0.000707   
2979 -0.399937 -0.229132  0.033803 -0.123612 -0.247684  0.016402 -0.014619   
2980 -0.375592 -0.236362  0.027785 -0.115981 -0.237280  0.021620  0.003884   
2981 -0.376352 -0.245924  0.025101 -0.108636 -0.241351  0.012499  0.000387   

             7         8         9  ...        55        56        57  \
0    -0.052221  0.023566  0.096095  ...  0.069402  0.113874 -0.182201   
1    -0.037921  0.046401  0.104943  ...  0.068049  0.127572 -0.184093   
2    -0.053261  0.017759  0.123539  ...  0.060476  0.122257 -0.199987   
3    -0.025417  0.023663  0.104899  ...  0.058609  0.131842 -0.174442   
4    -0.018375  0.029642  0.120596  ...  0.049452  0.133598 -0.193432   
...        ...       ...       ...  ...       ...       ...       ...   
2977 -0.068812  0.153218 -0.035892  ...  0.012855  0.015748 -0.197928   
2978 -0.070407  0.141462 -0.034134  ...  0.019306  0.026905 -0.197278   
2979 -0.058529  0.152670 -0.027237  ...  0.000301  0.020194 -0.206443   
2980 -0.082167  0.139204 -0.023313  ...  0.026507  0.027810 -0.202684   
2981 -0.082352  0.148581 -0.032882  ...  0.022828  0.017960 -0.192341   

            58        59        60        61        62        63  Class  
0     0.094850 -0.081999 -0.020652 -0.108172 -0.101368  0.107075      1  
1     0.097089 -0.092503 -0.004965 -0.119709 -0.108813  0.104411      1  
2     0.099250 -0.059540 -0.007854 -0.104801 -0.124797  0.150672      0  
3     0.101160 -0.093715 -0.020414 -0.102016 -0.104888  0.108388      0  
4     0.102704 -0.073113 -0.006345 -0.118883 -0.091774  0.127992      1  
...        ...       ...       ...       ...       ...       ...    ...  
2977  0.054717 -0.072942  0.030055 -0.187771 -0.090136 -0.094799      1  
2978  0.049776 -0.078077  0.016198 -0.179140 -0.096310 -0.067536      1  
2979  0.048825 -0.059514  0.022651 -0.194448 -0.091398 -0.070819      1  
2980  0.051592 -0.078311  0.020473 -0.187608 -0.093799 -0.061374      0  
2981  0.040386 -0.078194  0.021438 -0.185676 -0.095458 -0.066369      1  

[2982 rows x 65 columns]

Testing the model

In [31]:
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import classification_report,accuracy_score
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import metrics

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.metrics import confusion_matrix, recall_score, precision_score,f1_score
import seaborn as sns

In [32]:
X=node_emb.drop(['Class'],axis=1)
Y=node_emb['Class']

## MODEL BUILDING

### CROSS VALIDATION

In [33]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [34]:
from sklearn.svm import LinearSVC
models = LinearSVC()
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    models.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(models.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.5791415157612341
              precision    recall  f1-score   support

           0       0.40      0.00      0.01      1253
           1       0.58      1.00      0.73      1729

    accuracy                           0.58      2982
   macro avg       0.49      0.50      0.37      2982
weighted avg       0.50      0.58      0.43      2982

Confusion matrix:  [[   4 1249]
 [   6 1723]]


In [35]:
from sklearn.linear_model import PassiveAggressiveClassifier
pag=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    pag.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(pag.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.46981891348088534
              precision    recall  f1-score   support

           0       0.42      0.70      0.52      1253
           1       0.58      0.31      0.40      1729

    accuracy                           0.47      2982
   macro avg       0.50      0.50      0.46      2982
weighted avg       0.51      0.47      0.45      2982

Confusion matrix:  [[ 873  380]
 [1201  528]]


In [36]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=10000) 
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lr.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lr.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.57981220657277
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1253
           1       0.58      1.00      0.73      1729

    accuracy                           0.58      2982
   macro avg       0.29      0.50      0.37      2982
weighted avg       0.34      0.58      0.43      2982

Confusion matrix:  [[   0 1253]
 [   0 1729]]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [37]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
rf = RandomForestClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    rf.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(rf.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.5536552649228705
              precision    recall  f1-score   support

           0       0.43      0.18      0.26      1253
           1       0.58      0.82      0.68      1729

    accuracy                           0.55      2982
   macro avg       0.50      0.50      0.47      2982
weighted avg       0.52      0.55      0.50      2982

Confusion matrix:  [[ 231 1022]
 [ 309 1420]]


In [38]:
gbc = GradientBoostingClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    gbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(gbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.53420523138833
              precision    recall  f1-score   support

           0       0.41      0.24      0.30      1253
           1       0.58      0.75      0.65      1729

    accuracy                           0.53      2982
   macro avg       0.49      0.49      0.48      2982
weighted avg       0.50      0.53      0.50      2982

Confusion matrix:  [[ 298  955]
 [ 434 1295]]


In [39]:
abc = AdaBoostClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    abc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(abc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.5301810865191147
              precision    recall  f1-score   support

           0       0.42      0.31      0.35      1253
           1       0.58      0.69      0.63      1729

    accuracy                           0.53      2982
   macro avg       0.50      0.50      0.49      2982
weighted avg       0.51      0.53      0.51      2982

Confusion matrix:  [[ 383  870]
 [ 531 1198]]


In [40]:
import xgboost as xgb
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    xgbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(xgbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.5288397048960429
              precision    recall  f1-score   support

           0       0.42      0.32      0.37      1253
           1       0.58      0.68      0.63      1729

    accuracy                           0.53      2982
   macro avg       0.50      0.50      0.50      2982
weighted avg       0.51      0.53      0.52      2982

Confusion matrix:  [[ 405  848]
 [ 557 1172]]


In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=7, stratify=Y)

In [42]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
pa.fit(x_train, y_train)
y_pred=pa.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[251   0]
 [346   0]]
              precision    recall  f1-score   support

           0       0.42      1.00      0.59       251
           1       0.00      0.00      0.00       346

    accuracy                           0.42       597
   macro avg       0.21      0.50      0.30       597
weighted avg       0.18      0.42      0.25       597

accuracy_score:  0.4204355108877722


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [43]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
lsvm.fit(x_train, y_train)
y_pred=lsvm.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[  0 251]
 [  2 344]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       251
           1       0.58      0.99      0.73       346

    accuracy                           0.58       597
   macro avg       0.29      0.50      0.37       597
weighted avg       0.34      0.58      0.42       597

accuracy_score:  0.576214405360134


In [44]:
rf = RandomForestClassifier(n_estimators=300)
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[ 46 205]
 [ 75 271]]
              precision    recall  f1-score   support

           0       0.38      0.18      0.25       251
           1       0.57      0.78      0.66       346

    accuracy                           0.53       597
   macro avg       0.47      0.48      0.45       597
weighted avg       0.49      0.53      0.49       597

accuracy_score:  0.5309882747068677


In [45]:
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
xgbc.fit(x_train, y_train)
y_pred=xgbc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[ 87 164]
 [115 231]]
              precision    recall  f1-score   support

           0       0.43      0.35      0.38       251
           1       0.58      0.67      0.62       346

    accuracy                           0.53       597
   macro avg       0.51      0.51      0.50       597
weighted avg       0.52      0.53      0.52       597

accuracy_score:  0.5326633165829145


In [46]:
log = LogisticRegression(max_iter=10000) 
log.fit(x_train, y_train)
y_pred=log.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[  0 251]
 [  0 346]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       251
           1       0.58      1.00      0.73       346

    accuracy                           0.58       597
   macro avg       0.29      0.50      0.37       597
weighted avg       0.34      0.58      0.43       597

accuracy_score:  0.5795644891122278


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [47]:
gbc = GradientBoostingClassifier(n_estimators=300)
gbc.fit(x_train, y_train)
y_pred=gbc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[ 60 191]
 [ 81 265]]
              precision    recall  f1-score   support

           0       0.43      0.24      0.31       251
           1       0.58      0.77      0.66       346

    accuracy                           0.54       597
   macro avg       0.50      0.50      0.48       597
weighted avg       0.52      0.54      0.51       597

accuracy_score:  0.5443886097152428


In [48]:
abc = AdaBoostClassifier(n_estimators=300)
abc.fit(x_train, y_train)
y_pred=abc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[ 91 160]
 [114 232]]
              precision    recall  f1-score   support

           0       0.44      0.36      0.40       251
           1       0.59      0.67      0.63       346

    accuracy                           0.54       597
   macro avg       0.52      0.52      0.51       597
weighted avg       0.53      0.54      0.53       597

accuracy_score:  0.541038525963149


In [49]:
import lightgbm as lgb
lgb = lgb.LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=400, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
lgb.fit(x_train, y_train)
y_pred=lgb.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[ 84 167]
 [112 234]]
              precision    recall  f1-score   support

           0       0.43      0.33      0.38       251
           1       0.58      0.68      0.63       346

    accuracy                           0.53       597
   macro avg       0.51      0.51      0.50       597
weighted avg       0.52      0.53      0.52       597

accuracy_score:  0.5326633165829145
