In [1]:
!pip install stellargraph

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
!pip install networkx==2.3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
# importing all necessary libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import os
import networkx as nx
import stellargraph as sg
from stellargraph import StellarGraph
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
#from node2vec import Node2Vec as n2v
sns.set()

%matplotlib inline

In [4]:
df = pd.read_csv('Student-Employability-Dataset.csv')
df.head()
# Dataset is now stored in a Pandas Dataframe

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating           CLASS  
0                     5                           5      Employable  
1                     3                           5      Employable  
2                     2                           5  LessEmployable  
3                     3                           5  LessEmployable  
4                     3                           5      Employable

In [5]:
df.shape

(2982, 9)

In [6]:
df['CLASS'].value_counts()

Employable        1729
LessEmployable    1253
Name: CLASS, dtype: int64

In [7]:
z = {'Employable' : 1, 'LessEmployable' : 0}
df['CLASS'] = df['CLASS'].map(z)
df.head()

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating  CLASS  
0                     5                           5      1  
1                     3                           5      1  
2                     2                           5      0  
3                     3                           5      0  
4                     3                           5      1

In [8]:
#node_Class
node_Class = df["CLASS"]

In [9]:
u3=df.drop(['CLASS'], axis=1)
u3.head()

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating  
0                     5                           5  
1                     3                           5  
2                     2                           5  
3                     3                           5  
4                     3                           5

### Distance calculation for creating adjacency matrix


In [10]:
from scipy.spatial.distance import cdist
s = cdist(u3, u3, 'cosine')
s

array([[0.00000000e+00, 1.18196406e-02, 3.89451766e-02, ...,
        5.70574961e-03, 1.75078592e-02, 1.18196406e-02],
       [1.18196406e-02, 0.00000000e+00, 1.07846501e-02, ...,
        6.69736532e-03, 3.57110435e-03, 7.69230769e-03],
       [3.89451766e-02, 1.07846501e-02, 0.00000000e+00, ...,
        2.63323597e-02, 1.15390226e-02, 2.00296533e-02],
       ...,
       [5.70574961e-03, 6.69736532e-03, 2.63323597e-02, ...,
        0.00000000e+00, 1.50356688e-02, 6.69736532e-03],
       [1.75078592e-02, 3.57110435e-03, 1.15390226e-02, ...,
        1.50356688e-02, 1.11022302e-16, 1.14792702e-02],
       [1.18196406e-02, 7.69230769e-03, 2.00296533e-02, ...,
        6.69736532e-03, 1.14792702e-02, 0.00000000e+00]])

In [11]:
X1=pd.DataFrame(s)
X1

0         1         2         3         4         5         6     \
0     0.000000  0.011820  0.038945  0.031784  0.015827  0.023852  0.023828   
1     0.011820  0.000000  0.010785  0.018050  0.006520  0.010005  0.017776   
2     0.038945  0.010785  0.000000  0.016536  0.011513  0.008478  0.038122   
3     0.031784  0.018050  0.016536  0.000000  0.011438  0.010986  0.043910   
4     0.015827  0.006520  0.011513  0.011438  0.000000  0.007125  0.027587   
...        ...       ...       ...       ...       ...       ...       ...   
2977  0.038945  0.010785  0.000000  0.016536  0.011513  0.008478  0.038122   
2978  0.005318  0.007692  0.029275  0.018050  0.014663  0.018689  0.026871   
2979  0.005706  0.006697  0.026332  0.030187  0.015583  0.013821  0.017178   
2980  0.017508  0.003571  0.011539  0.010289  0.003757  0.009008  0.018263   
2981  0.011820  0.007692  0.020030  0.018050  0.014663  0.010005  0.017776   

          7         8         9     ...      2972      2973      2974  \
0     0.036119  0.005732  0.010824  ...  0.055234  0.021551  0.015827   
1     0.017689  0.003403  0.011479  ...  0.039031  0.008924  0.006520   
2     0.009505  0.018376  0.021043  ...  0.021836  0.019694  0.011513   
3     0.031092  0.015332  0.020186  ...  0.030511  0.023098  0.021630   
4     0.021789  0.008436  0.012128  ...  0.034596  0.015815  0.008621   
...        ...       ...       ...  ...       ...       ...       ...   
2977  0.009505  0.018376  0.021043  ...  0.021836  0.019694  0.011513   
2978  0.034339  0.003403  0.011479  ...  0.048837  0.017695  0.014663   
2979  0.024151  0.004957  0.007793  ...  0.039112  0.020072  0.008125   
2980  0.024357  0.006251  0.016260  ...  0.042308  0.008163  0.012128   
2981  0.017689  0.003403  0.003571  ...  0.029225  0.017695  0.006520   

          2975      2976      2977      2978      2979          2980      2981  
0     0.022710  0.031191  0.038945  0.005318  0.005706  1.750786e-02  0.011820  
1     0.006520  0.018689  0.010785  0.007692  0.006697  3.571104e-03  0.007692  
2     0.011513  0.018915  0.000000  0.029275  0.026332  1.153902e-02  0.020030  
3     0.021630  0.043591  0.016536  0.018050  0.030187  1.028900e-02  0.018050  
4     0.017241  0.025511  0.011513  0.014663  0.015583  3.756706e-03  0.014663  
...        ...       ...       ...       ...       ...           ...       ...  
2977  0.011513  0.018915  0.000000  0.029275  0.026332  1.153902e-02  0.020030  
2978  0.014663  0.036057  0.029275  0.000000  0.006697  1.147927e-02  0.007692  
2979  0.008125  0.021774  0.026332  0.006697  0.000000  1.503567e-02  0.006697  
2980  0.012128  0.026863  0.011539  0.011479  0.015036  1.110223e-16  0.011479  
2981  0.006520  0.018689  0.020030  0.007692  0.006697  1.147927e-02  0.000000  

[2982 rows x 2982 columns]

In [12]:
# taking average of the hamming distance matrix
y = np.average(X1)
y

0.01856620671593297

In [13]:
adjmat_df=X1.copy()

In [14]:
# setting threshold value as mean of hamming matrix
adjmat_df[adjmat_df < y]=0
adjmat_df[adjmat_df >= y]=1

In [15]:
# adjacency matrix
adjmat_df

0     1     2     3     4     5     6     7     8     9     ...  2972  \
0      0.0   0.0   1.0   1.0   0.0   1.0   1.0   1.0   0.0   0.0  ...   1.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   1.0   
2      1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  ...   1.0   
3      1.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   1.0  ...   1.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0  ...   1.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2977   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  ...   1.0   
2978   0.0   0.0   1.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0  ...   1.0   
2979   0.0   0.0   1.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0  ...   1.0   
2980   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  ...   1.0   
2981   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   1.0   

      2973  2974  2975  2976  2977  2978  2979  2980  2981  
0      1.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
2      1.0   0.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0  
3      1.0   1.0   1.0   1.0   0.0   0.0   1.0   0.0   0.0  
4      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2977   1.0   0.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0  
2978   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  
2979   1.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  
2980   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
2981   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  

[2982 rows x 2982 columns]

In [16]:
G = nx.from_numpy_matrix(np.array(adjmat_df))
G

In [17]:
A=nx.to_numpy_matrix(G)
##Creating graph from adjacency matrix
H=nx.from_numpy_matrix(A)

### Construct a graph using stellargraph

In [18]:
square_feature_dataframe = StellarGraph.from_networkx(H, node_features=adjmat_df)
print(square_feature_dataframe.info())

StellarGraph: Undirected multigraph
 Nodes: 2982, Edges: 1793526

 Node types:
  default: [2982]
    Features: float32 vector, length 2982
    Edge types: default-default->default

 Edge types:
    default-default->default: [1793526]
        Weights: all 1 (default)
        Features: none


In [19]:
from stellargraph.mapper import (
    CorruptedGenerator,
    FullBatchNodeGenerator,
    GraphSAGENodeGenerator,
    HinSAGENodeGenerator,
    ClusterNodeGenerator,
)
from stellargraph import StellarGraph
from stellargraph.layer import GCN, DeepGraphInfomax, GraphSAGE, GAT, APPNP, HinSAGE

from stellargraph import datasets
from stellargraph.utils import plot_history

import pandas as pd
from matplotlib import pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.manifold import TSNE
from IPython.display import display, HTML

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
from tensorflow.keras import Model

### Data Generators
Now we create the data generators using CorruptedGenerator (docs). CorruptedGenerator returns shuffled node features along with the regular node features and we train our model to discriminate between the two.

In [20]:
fullbatch_generator = FullBatchNodeGenerator(square_feature_dataframe, sparse=False)
fullbatch_generator 

Using GCN (local pooling) filters...


In [21]:
gcn_model = GCN(layer_sizes=[128], activations=["relu"], generator=fullbatch_generator)
gcn_model

In [22]:
corrupted_generator = CorruptedGenerator(fullbatch_generator)
gen = corrupted_generator.flow(square_feature_dataframe.nodes())

### GCN Model Creation and Training
We create and train our DeepGraphInfomax model (docs). Note that the loss used here must always be tf.nn.sigmoid_cross_entropy_with_logits.



In [23]:
infomax = DeepGraphInfomax(gcn_model, corrupted_generator)
x_in, x_out = infomax.in_out_tensors()

In [24]:
model = Model(inputs=x_in, outputs=x_out)
model.compile(loss=tf.nn.sigmoid_cross_entropy_with_logits, optimizer=Adam(lr=1e-3))

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


###Extracting Embeddings

In [25]:
x_emb_in, x_emb_out = gcn_model.in_out_tensors()

# for full batch models, squeeze out the batch dim (which is 1)
x_out = tf.squeeze(x_emb_out, axis=0)
emb_model = Model(inputs=x_emb_in, outputs=x_out)

In [26]:
all_nodes = df['CLASS'].index
all_gen = fullbatch_generator.flow(all_nodes)

In [27]:
emb = emb_model.predict(all_gen)
emb.shape

1/1 [==============================] - 1s 1s/step


(2982, 128)

In [28]:
emb

array([[0.        , 1.1496813 , 0.        , ..., 0.6291293 , 0.        ,
        0.        ],
       [0.        , 0.9183435 , 0.11501129, ..., 0.26387554, 0.1609807 ,
        0.12745453],
       [0.        , 1.1550078 , 0.24978502, ..., 0.23881315, 0.06931163,
        0.0837152 ],
       ...,
       [0.        , 1.1205025 , 0.12614216, ..., 0.5191006 , 0.        ,
        0.        ],
       [0.        , 0.94138724, 0.16301459, ..., 0.28293824, 0.0833326 ,
        0.21759696],
       [0.        , 1.0142957 , 0.09808087, ..., 0.3890053 , 0.00627269,
        0.15927014]], dtype=float32)

In [29]:
node_emb = pd.DataFrame(emb)

In [30]:
node_emb['Class']=node_Class

In [31]:
node_emb

0         1         2         3         4    5         6    7    8  \
0     0.0  1.149681  0.000000  1.138953  1.098174  0.0  0.004287  0.0  0.0   
1     0.0  0.918343  0.115011  0.793869  0.953483  0.0  0.073865  0.0  0.0   
2     0.0  1.155008  0.249785  1.403196  1.595020  0.0  0.077529  0.0  0.0   
3     0.0  1.210319  0.077790  1.524827  1.605236  0.0  0.059882  0.0  0.0   
4     0.0  1.009542  0.155613  1.166863  1.209843  0.0  0.128220  0.0  0.0   
...   ...       ...       ...       ...       ...  ...       ...  ...  ...   
2977  0.0  1.155008  0.249785  1.403196  1.595020  0.0  0.077529  0.0  0.0   
2978  0.0  1.146836  0.053161  1.018056  1.043486  0.0  0.128202  0.0  0.0   
2979  0.0  1.120502  0.126142  0.988662  1.128228  0.0  0.000000  0.0  0.0   
2980  0.0  0.941387  0.163015  0.874389  1.041948  0.0  0.097989  0.0  0.0   
2981  0.0  1.014296  0.098081  0.769285  1.001123  0.0  0.027920  0.0  0.0   

             9  ...       119       120       121       122  123  124  \
0     0.291106  ...  0.000000  0.237814  0.000000  0.301777  0.0  0.0   
1     0.114449  ...  0.133285  0.000000  0.390443  0.000000  0.0  0.0   
2     0.498909  ...  0.539091  0.000000  0.378708  0.000000  0.0  0.0   
3     0.609787  ...  0.590275  0.000000  0.247563  0.000000  0.0  0.0   
4     0.177452  ...  0.196624  0.000000  0.478014  0.000000  0.0  0.0   
...        ...  ...       ...       ...       ...       ...  ...  ...   
2977  0.498909  ...  0.539092  0.000000  0.378708  0.000000  0.0  0.0   
2978  0.182002  ...  0.009242  0.000000  0.243212  0.000000  0.0  0.0   
2979  0.125999  ...  0.000000  0.113902  0.102344  0.000000  0.0  0.0   
2980  0.119053  ...  0.160188  0.000000  0.477572  0.000000  0.0  0.0   
2981  0.043099  ...  0.102107  0.000000  0.396830  0.000000  0.0  0.0   

           125       126       127  Class  
0     0.629129  0.000000  0.000000      1  
1     0.263876  0.160981  0.127455      1  
2     0.238813  0.069312  0.083715      0  
3     0.388576  0.000000  0.058665      0  
4     0.312843  0.000000  0.093909      1  
...        ...       ...       ...    ...  
2977  0.238813  0.069312  0.083715      1  
2978  0.482767  0.000000  0.065321      1  
2979  0.519101  0.000000  0.000000      1  
2980  0.282938  0.083333  0.217597      0  
2981  0.389005  0.006273  0.159270      1  

[2982 rows x 129 columns]

In [32]:
X=node_emb.drop(['Class'],axis=1)
Y=node_emb['Class']

### MODEL BUILDING

### 10 FOLD CROSS VALIDATION

In [33]:
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import classification_report,accuracy_score
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import metrics

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.metrics import confusion_matrix, recall_score, precision_score,f1_score
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [34]:
from sklearn.svm import LinearSVC
models = LinearSVC()
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    models.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(models.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.7662642521797451
              precision    recall  f1-score   support

           0       0.72      0.73      0.72      1253
           1       0.80      0.79      0.80      1729

    accuracy                           0.77      2982
   macro avg       0.76      0.76      0.76      2982
weighted avg       0.77      0.77      0.77      2982

Confusion matrix:  [[ 912  341]
 [ 356 1373]]


In [35]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=10000) 
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lr.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lr.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.7263581488933601
              precision    recall  f1-score   support

           0       0.68      0.66      0.67      1253
           1       0.76      0.77      0.77      1729

    accuracy                           0.73      2982
   macro avg       0.72      0.72      0.72      2982
weighted avg       0.73      0.73      0.73      2982

Confusion matrix:  [[ 828  425]
 [ 391 1338]]


In [36]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
rf = RandomForestClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    rf.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(rf.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.8960429242119383
              precision    recall  f1-score   support

           0       0.89      0.86      0.87      1253
           1       0.90      0.92      0.91      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.89      0.89      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1076  177]
 [ 133 1596]]


In [37]:
gbc = GradientBoostingClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    gbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(gbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.8967136150234741
              precision    recall  f1-score   support

           0       0.89      0.86      0.88      1253
           1       0.90      0.92      0.91      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.89      0.89      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1079  174]
 [ 134 1595]]


In [38]:
import xgboost as xgb
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    xgbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(xgbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.8735747820254862
              precision    recall  f1-score   support

           0       0.86      0.83      0.85      1253
           1       0.88      0.90      0.89      1729

    accuracy                           0.87      2982
   macro avg       0.87      0.87      0.87      2982
weighted avg       0.87      0.87      0.87      2982

Confusion matrix:  [[1044  209]
 [ 168 1561]]


In [39]:
import lightgbm as lgb
lgb = lgb.LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=400, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lgb.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lgb.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.8608316566063045
              precision    recall  f1-score   support

           0       0.85      0.82      0.83      1253
           1       0.87      0.89      0.88      1729

    accuracy                           0.86      2982
   macro avg       0.86      0.85      0.86      2982
weighted avg       0.86      0.86      0.86      2982

Confusion matrix:  [[1023  230]
 [ 185 1544]]


### TRAIN TEST SPLIT

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=7, stratify=Y)

In [41]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
pa.fit(x_train, y_train)
y_pred=pa.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[228  23]
 [202 144]]
              precision    recall  f1-score   support

           0       0.53      0.91      0.67       251
           1       0.86      0.42      0.56       346

    accuracy                           0.62       597
   macro avg       0.70      0.66      0.62       597
weighted avg       0.72      0.62      0.61       597

accuracy_score:  0.6231155778894473


In [42]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
lsvm.fit(x_train, y_train)
y_pred=lsvm.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[191  60]
 [ 75 271]]
              precision    recall  f1-score   support

           0       0.72      0.76      0.74       251
           1       0.82      0.78      0.80       346

    accuracy                           0.77       597
   macro avg       0.77      0.77      0.77       597
weighted avg       0.78      0.77      0.77       597

accuracy_score:  0.7738693467336684


In [43]:
rf = RandomForestClassifier(n_estimators=300)
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[216  35]
 [ 21 325]]
              precision    recall  f1-score   support

           0       0.91      0.86      0.89       251
           1       0.90      0.94      0.92       346

    accuracy                           0.91       597
   macro avg       0.91      0.90      0.90       597
weighted avg       0.91      0.91      0.91       597

accuracy_score:  0.9061976549413735


In [44]:
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
xgbc.fit(x_train, y_train)
y_pred=xgbc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[214  37]
 [ 36 310]]
              precision    recall  f1-score   support

           0       0.86      0.85      0.85       251
           1       0.89      0.90      0.89       346

    accuracy                           0.88       597
   macro avg       0.87      0.87      0.87       597
weighted avg       0.88      0.88      0.88       597

accuracy_score:  0.8777219430485762


In [45]:
log = LogisticRegression(max_iter=10000) 
log.fit(x_train, y_train)
y_pred=log.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[170  81]
 [ 82 264]]
              precision    recall  f1-score   support

           0       0.67      0.68      0.68       251
           1       0.77      0.76      0.76       346

    accuracy                           0.73       597
   macro avg       0.72      0.72      0.72       597
weighted avg       0.73      0.73      0.73       597

accuracy_score:  0.7269681742043551
