In [51]:
!pip install stellargraph

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [52]:
!pip install networkx==2.3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [53]:
# importing all necessary libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import os
import networkx as nx
import stellargraph as sg
from stellargraph import StellarGraph
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
#from node2vec import Node2Vec as n2v
sns.set()

%matplotlib inline

In [54]:
df = pd.read_csv('Student-Employability-Dataset.csv')
df.head()
# Dataset is now stored in a Pandas Dataframe

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating           CLASS  
0                     5                           5      Employable  
1                     3                           5      Employable  
2                     2                           5  LessEmployable  
3                     3                           5  LessEmployable  
4                     3                           5      Employable

In [55]:
df.shape

(2982, 9)

In [56]:
df['CLASS'].value_counts()

Employable        1729
LessEmployable    1253
Name: CLASS, dtype: int64

In [57]:
z = {'Employable' : 1, 'LessEmployable' : 0}
df['CLASS'] = df['CLASS'].map(z)
df.head()

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating  CLASS  
0                     5                           5      1  
1                     3                           5      1  
2                     2                           5      0  
3                     3                           5      0  
4                     3                           5      1

In [58]:
#node_Class
node_Class = df["CLASS"]

In [59]:
u3=df.drop(['CLASS'], axis=1)
u3.head()

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating  
0                     5                           5  
1                     3                           5  
2                     2                           5  
3                     3                           5  
4                     3                           5

### Distance calculation for creating adjacency matrix


In [60]:
from scipy.spatial.distance import cdist
s = cdist(u3, u3, 'cosine')
s

array([[0.00000000e+00, 1.18196406e-02, 3.89451766e-02, ...,
        5.70574961e-03, 1.75078592e-02, 1.18196406e-02],
       [1.18196406e-02, 0.00000000e+00, 1.07846501e-02, ...,
        6.69736532e-03, 3.57110435e-03, 7.69230769e-03],
       [3.89451766e-02, 1.07846501e-02, 0.00000000e+00, ...,
        2.63323597e-02, 1.15390226e-02, 2.00296533e-02],
       ...,
       [5.70574961e-03, 6.69736532e-03, 2.63323597e-02, ...,
        0.00000000e+00, 1.50356688e-02, 6.69736532e-03],
       [1.75078592e-02, 3.57110435e-03, 1.15390226e-02, ...,
        1.50356688e-02, 1.11022302e-16, 1.14792702e-02],
       [1.18196406e-02, 7.69230769e-03, 2.00296533e-02, ...,
        6.69736532e-03, 1.14792702e-02, 0.00000000e+00]])

In [61]:
X1=pd.DataFrame(s)
X1

0         1         2         3         4         5         6     \
0     0.000000  0.011820  0.038945  0.031784  0.015827  0.023852  0.023828   
1     0.011820  0.000000  0.010785  0.018050  0.006520  0.010005  0.017776   
2     0.038945  0.010785  0.000000  0.016536  0.011513  0.008478  0.038122   
3     0.031784  0.018050  0.016536  0.000000  0.011438  0.010986  0.043910   
4     0.015827  0.006520  0.011513  0.011438  0.000000  0.007125  0.027587   
...        ...       ...       ...       ...       ...       ...       ...   
2977  0.038945  0.010785  0.000000  0.016536  0.011513  0.008478  0.038122   
2978  0.005318  0.007692  0.029275  0.018050  0.014663  0.018689  0.026871   
2979  0.005706  0.006697  0.026332  0.030187  0.015583  0.013821  0.017178   
2980  0.017508  0.003571  0.011539  0.010289  0.003757  0.009008  0.018263   
2981  0.011820  0.007692  0.020030  0.018050  0.014663  0.010005  0.017776   

          7         8         9     ...      2972      2973      2974  \
0     0.036119  0.005732  0.010824  ...  0.055234  0.021551  0.015827   
1     0.017689  0.003403  0.011479  ...  0.039031  0.008924  0.006520   
2     0.009505  0.018376  0.021043  ...  0.021836  0.019694  0.011513   
3     0.031092  0.015332  0.020186  ...  0.030511  0.023098  0.021630   
4     0.021789  0.008436  0.012128  ...  0.034596  0.015815  0.008621   
...        ...       ...       ...  ...       ...       ...       ...   
2977  0.009505  0.018376  0.021043  ...  0.021836  0.019694  0.011513   
2978  0.034339  0.003403  0.011479  ...  0.048837  0.017695  0.014663   
2979  0.024151  0.004957  0.007793  ...  0.039112  0.020072  0.008125   
2980  0.024357  0.006251  0.016260  ...  0.042308  0.008163  0.012128   
2981  0.017689  0.003403  0.003571  ...  0.029225  0.017695  0.006520   

          2975      2976      2977      2978      2979          2980      2981  
0     0.022710  0.031191  0.038945  0.005318  0.005706  1.750786e-02  0.011820  
1     0.006520  0.018689  0.010785  0.007692  0.006697  3.571104e-03  0.007692  
2     0.011513  0.018915  0.000000  0.029275  0.026332  1.153902e-02  0.020030  
3     0.021630  0.043591  0.016536  0.018050  0.030187  1.028900e-02  0.018050  
4     0.017241  0.025511  0.011513  0.014663  0.015583  3.756706e-03  0.014663  
...        ...       ...       ...       ...       ...           ...       ...  
2977  0.011513  0.018915  0.000000  0.029275  0.026332  1.153902e-02  0.020030  
2978  0.014663  0.036057  0.029275  0.000000  0.006697  1.147927e-02  0.007692  
2979  0.008125  0.021774  0.026332  0.006697  0.000000  1.503567e-02  0.006697  
2980  0.012128  0.026863  0.011539  0.011479  0.015036  1.110223e-16  0.011479  
2981  0.006520  0.018689  0.020030  0.007692  0.006697  1.147927e-02  0.000000  

[2982 rows x 2982 columns]

In [62]:
# taking average of the hamming distance matrix
y = np.average(X1)
y

0.01856620671593297

In [63]:
adjmat_df=X1.copy()

In [64]:
# setting threshold value as mean of hamming matrix
adjmat_df[adjmat_df < y]=0
adjmat_df[adjmat_df >= y]=1

In [65]:
# adjacency matrix
adjmat_df

0     1     2     3     4     5     6     7     8     9     ...  2972  \
0      0.0   0.0   1.0   1.0   0.0   1.0   1.0   1.0   0.0   0.0  ...   1.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   1.0   
2      1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  ...   1.0   
3      1.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   1.0  ...   1.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0  ...   1.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2977   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  ...   1.0   
2978   0.0   0.0   1.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0  ...   1.0   
2979   0.0   0.0   1.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0  ...   1.0   
2980   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  ...   1.0   
2981   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   1.0   

      2973  2974  2975  2976  2977  2978  2979  2980  2981  
0      1.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
2      1.0   0.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0  
3      1.0   1.0   1.0   1.0   0.0   0.0   1.0   0.0   0.0  
4      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2977   1.0   0.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0  
2978   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  
2979   1.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  
2980   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
2981   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  

[2982 rows x 2982 columns]

In [66]:
G = nx.from_numpy_matrix(np.array(adjmat_df))
G

In [67]:
A=nx.to_numpy_matrix(G)
##Creating graph from adjacency matrix
H=nx.from_numpy_matrix(A)

### Construct a graph using stellargraph

In [68]:
square_feature_dataframe = StellarGraph.from_networkx(H, node_features=adjmat_df)
print(square_feature_dataframe.info())

StellarGraph: Undirected multigraph
 Nodes: 2982, Edges: 1793526

 Node types:
  default: [2982]
    Features: float32 vector, length 2982
    Edge types: default-default->default

 Edge types:
    default-default->default: [1793526]
        Weights: all 1 (default)
        Features: none


In [69]:
from stellargraph.mapper import (
    CorruptedGenerator,
    FullBatchNodeGenerator,
    GraphSAGENodeGenerator,
    HinSAGENodeGenerator,
    ClusterNodeGenerator,
)
from stellargraph import StellarGraph
from stellargraph.layer import GCN, DeepGraphInfomax, GraphSAGE, GAT, APPNP, HinSAGE
from stellargraph.mapper import FullBatchNodeGenerator
from stellargraph.layer.ppnp import PPNP
from stellargraph.layer.appnp import APPNP
from stellargraph.mapper import ClusterNodeGenerator
from stellargraph import datasets
from stellargraph.utils import plot_history
from tensorflow.keras import layers, optimizers, losses, metrics, Model, regularizers
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.manifold import TSNE
from IPython.display import display, HTML

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
from tensorflow.keras import Model

### Node Generator

In [70]:
generator = FullBatchNodeGenerator(square_feature_dataframe, method="ppnp", sparse=False, teleport_probability=0.1)
generator 

In [71]:
target_encoding = preprocessing.LabelBinarizer()

targets = target_encoding.fit_transform(df['CLASS'])
targets

array([[1],
       [1],
       [0],
       ...,
       [1],
       [0],
       [1]])

In [72]:
targets.shape[1]

1

In [73]:
from tensorflow import keras
ppnp = PPNP(
    layer_sizes=[32, 32, 32],
    activations=["relu", "relu", "softmax"],
    generator=generator,
    dropout=0.5,
    kernel_regularizer=keras.regularizers.l2(0.001),
)
ppnp

In [74]:
# Expose the input and output tensors of the ppnp model for node prediction,
# via GCN.in_out_tensors() method:
x_inp, x_out = ppnp.in_out_tensors()

In [75]:
x_inp

[<KerasTensor: shape=(1, 2982, 2982) dtype=float32 (created by layer 'input_5')>,
 <KerasTensor: shape=(1, None) dtype=int32 (created by layer 'input_6')>,
 <KerasTensor: shape=(1, 2982, 2982) dtype=float32 (created by layer 'input_7')>]

In [76]:
x_out

<KerasTensor: shape=(1, None, 32) dtype=float32 (created by layer 'gather_indices_1')>

In [77]:
predictions = keras.layers.Softmax()(x_out)
predictions

<KerasTensor: shape=(1, None, 32) dtype=float32 (created by layer 'softmax')>

In [78]:
model = Model(inputs=x_inp, outputs=predictions)

In [79]:
#model = Model(inputs=x_inp, outputs=x_out)

### Node embeddings

In [80]:
all_nodes = df['CLASS'].index
all_nodes

RangeIndex(start=0, stop=2982, step=1)

In [81]:
all_gen = generator.flow(all_nodes)
all_gen

In [82]:
emb = model.predict(all_gen)
emb.shape

1/1 [==============================] - 0s 148ms/step


(1, 2982, 32)

In [83]:
emb

array([[[0.03164475, 0.03150815, 0.03116417, ..., 0.03113127,
         0.0307456 , 0.03222492],
        [0.0315432 , 0.03141576, 0.03121219, ..., 0.0311375 ,
         0.03095048, 0.03186817],
        [0.03176034, 0.03163778, 0.03112304, ..., 0.03102976,
         0.03063453, 0.03253619],
        ...,
        [0.03164616, 0.03144648, 0.03118033, ..., 0.03112351,
         0.03083704, 0.03205561],
        [0.0315801 , 0.03143486, 0.03122676, ..., 0.03109059,
         0.03087626, 0.03200551],
        [0.03158804, 0.03148124, 0.03117698, ..., 0.03110063,
         0.0308781 , 0.03198106]]], dtype=float32)

In [84]:
w = emb.squeeze()

In [85]:
node_emb = pd.DataFrame(w)

In [86]:
y = df['CLASS']
y

0       1
1       1
2       0
3       0
4       1
       ..
2977    1
2978    1
2979    1
2980    0
2981    1
Name: CLASS, Length: 2982, dtype: int64

In [87]:
node_emb['Class']=y

In [88]:
node_emb

0         1         2         3         4         5         6  \
0     0.031645  0.031508  0.031164  0.030698  0.031804  0.031177  0.030686   
1     0.031543  0.031416  0.031212  0.030879  0.031656  0.031253  0.030875   
2     0.031760  0.031638  0.031123  0.030544  0.032020  0.031184  0.030556   
3     0.031793  0.031662  0.031098  0.030484  0.032048  0.031170  0.030494   
4     0.031706  0.031506  0.031184  0.030711  0.031835  0.031220  0.030703   
...        ...       ...       ...       ...       ...       ...       ...   
2977  0.031760  0.031638  0.031123  0.030544  0.032020  0.031184  0.030556   
2978  0.031701  0.031529  0.031178  0.030735  0.031788  0.031257  0.030739   
2979  0.031646  0.031446  0.031180  0.030751  0.031742  0.031238  0.030743   
2980  0.031580  0.031435  0.031227  0.030817  0.031692  0.031235  0.030813   
2981  0.031588  0.031481  0.031177  0.030809  0.031744  0.031252  0.030814   

             7         8         9  ...        23        24        25  \
0     0.031603  0.030921  0.031754  ...  0.031413  0.031218  0.031107   
1     0.031478  0.031057  0.031556  ...  0.031352  0.031224  0.031171   
2     0.031710  0.030888  0.031927  ...  0.031443  0.031210  0.031080   
3     0.031713  0.030803  0.032011  ...  0.031471  0.031199  0.031061   
4     0.031628  0.030986  0.031744  ...  0.031432  0.031214  0.031151   
...        ...       ...       ...  ...       ...       ...       ...   
2977  0.031710  0.030888  0.031927  ...  0.031443  0.031210  0.031080   
2978  0.031575  0.030984  0.031698  ...  0.031404  0.031222  0.031126   
2979  0.031542  0.030958  0.031675  ...  0.031393  0.031196  0.031122   
2980  0.031551  0.031028  0.031613  ...  0.031396  0.031220  0.031177   
2981  0.031544  0.031012  0.031631  ...  0.031363  0.031236  0.031140   

            26        27        28        29        30        31  Class  
0     0.030955  0.030576  0.031095  0.031131  0.030746  0.032225      1  
1     0.031045  0.030811  0.031156  0.031138  0.030950  0.031868      1  
2     0.030840  0.030421  0.031036  0.031030  0.030635  0.032536      0  
3     0.030808  0.030338  0.031033  0.031022  0.030575  0.032679      0  
4     0.030952  0.030621  0.031116  0.031057  0.030785  0.032203      1  
...        ...       ...       ...       ...       ...       ...    ...  
2977  0.030840  0.030421  0.031036  0.031030  0.030635  0.032536      1  
2978  0.030967  0.030651  0.031106  0.031079  0.030825  0.032114      1  
2979  0.030970  0.030656  0.031130  0.031124  0.030837  0.032056      1  
2980  0.031001  0.030743  0.031159  0.031091  0.030876  0.032006      0  
2981  0.030991  0.030743  0.031140  0.031101  0.030878  0.031981      1  

[2982 rows x 33 columns]

In [89]:
X=node_emb.drop(['Class'],axis=1)
Y=node_emb['Class']

In [90]:
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import classification_report,accuracy_score
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import metrics

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.metrics import confusion_matrix, recall_score, precision_score,f1_score
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [91]:
from sklearn.svm import LinearSVC
models = LinearSVC()
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    models.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(models.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.57981220657277
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1253
           1       0.58      1.00      0.73      1729

    accuracy                           0.58      2982
   macro avg       0.29      0.50      0.37      2982
weighted avg       0.34      0.58      0.43      2982

Confusion matrix:  [[   0 1253]
 [   0 1729]]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [92]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=10000) 
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lr.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lr.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.57981220657277
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1253
           1       0.58      1.00      0.73      1729

    accuracy                           0.58      2982
   macro avg       0.29      0.50      0.37      2982
weighted avg       0.34      0.58      0.43      2982

Confusion matrix:  [[   0 1253]
 [   0 1729]]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [93]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
rf = RandomForestClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    rf.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(rf.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9010731052984574
              precision    recall  f1-score   support

           0       0.90      0.86      0.88      1253
           1       0.90      0.93      0.92      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.90      0.90      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1083  170]
 [ 125 1604]]


In [94]:
gbc = GradientBoostingClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    gbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(gbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.898054996646546
              precision    recall  f1-score   support

           0       0.90      0.85      0.88      1253
           1       0.90      0.93      0.91      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.89      0.89      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1069  184]
 [ 120 1609]]


In [95]:
import xgboost as xgb
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    xgbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(xgbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9057679409792085
              precision    recall  f1-score   support

           0       0.90      0.87      0.89      1253
           1       0.91      0.93      0.92      1729

    accuracy                           0.91      2982
   macro avg       0.91      0.90      0.90      2982
weighted avg       0.91      0.91      0.91      2982

Confusion matrix:  [[1091  162]
 [ 119 1610]]


In [96]:
import lightgbm as lgb
lgb = lgb.LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=400, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lgb.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lgb.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9071093226022804
              precision    recall  f1-score   support

           0       0.90      0.88      0.89      1253
           1       0.91      0.93      0.92      1729

    accuracy                           0.91      2982
   macro avg       0.91      0.90      0.90      2982
weighted avg       0.91      0.91      0.91      2982

Confusion matrix:  [[1103  150]
 [ 127 1602]]


In [97]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=7, stratify=Y)

In [98]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
pa.fit(x_train, y_train)
y_pred=pa.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[251   0]
 [346   0]]
              precision    recall  f1-score   support

           0       0.42      1.00      0.59       251
           1       0.00      0.00      0.00       346

    accuracy                           0.42       597
   macro avg       0.21      0.50      0.30       597
weighted avg       0.18      0.42      0.25       597

accuracy_score:  0.4204355108877722


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [99]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
lsvm.fit(x_train, y_train)
y_pred=lsvm.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[  0 251]
 [  0 346]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       251
           1       0.58      1.00      0.73       346

    accuracy                           0.58       597
   macro avg       0.29      0.50      0.37       597
weighted avg       0.34      0.58      0.43       597

accuracy_score:  0.5795644891122278


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [100]:
rf = RandomForestClassifier(n_estimators=300)
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[217  34]
 [ 21 325]]
              precision    recall  f1-score   support

           0       0.91      0.86      0.89       251
           1       0.91      0.94      0.92       346

    accuracy                           0.91       597
   macro avg       0.91      0.90      0.90       597
weighted avg       0.91      0.91      0.91       597

accuracy_score:  0.9078726968174204


In [101]:
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
xgbc.fit(x_train, y_train)
y_pred=xgbc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[217  34]
 [ 21 325]]
              precision    recall  f1-score   support

           0       0.91      0.86      0.89       251
           1       0.91      0.94      0.92       346

    accuracy                           0.91       597
   macro avg       0.91      0.90      0.90       597
weighted avg       0.91      0.91      0.91       597

accuracy_score:  0.9078726968174204


In [102]:
log = LogisticRegression(max_iter=10000) 
log.fit(x_train, y_train)
y_pred=log.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[  0 251]
 [  0 346]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       251
           1       0.58      1.00      0.73       346

    accuracy                           0.58       597
   macro avg       0.29      0.50      0.37       597
weighted avg       0.34      0.58      0.43       597

accuracy_score:  0.5795644891122278


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
