In [1]:
!pip install stellargraph

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 435.2/435.2 KB 7.8 MB/s eta 0:00:00


In [2]:
!pip install networkx==2.3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 23.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for networkx: filename=networkx-2.3-py2.py3-none-any.whl size=1556009 sha256=c628de466b11e5e12dfde45745483348fc7681668148ac9df40f18617286f54b
  Stored in directory: /root/.cache/pip/wheels/ff/62/9e/0ed2d25fd4f5761e2d19568cda0c32716556dfa682e65ecf64
Successfully built networkx
  Attempting uninstall: networkx
    Found existing installation: networkx 3.0
    Uninstalling networkx-3.0:
      Successfully uninstalled networkx-3.0


In [3]:
# importing all necessary libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import os
import networkx as nx
import stellargraph as sg
from stellargraph import StellarGraph
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
#from node2vec import Node2Vec as n2v
sns.set()

%matplotlib inline

In [4]:
df = pd.read_csv('Student-Employability-Dataset.csv')
df.head()
# Dataset is now stored in a Pandas Dataframe

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating           CLASS  
0                     5                           5      Employable  
1                     3                           5      Employable  
2                     2                           5  LessEmployable  
3                     3                           5  LessEmployable  
4                     3                           5      Employable

In [5]:
df.shape

(2982, 9)

In [6]:
df['CLASS'].value_counts()

Employable        1729
LessEmployable    1253
Name: CLASS, dtype: int64

In [7]:
z = {'Employable' : 1, 'LessEmployable' : 0}
df['CLASS'] = df['CLASS'].map(z)
df.head()

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating  CLASS  
0                     5                           5      1  
1                     3                           5      1  
2                     2                           5      0  
3                     3                           5      0  
4                     3                           5      1

In [8]:
#node_Class
node_Class = df["CLASS"]

In [9]:
u3=df.drop(['CLASS'], axis=1)
u3.head()

GENERAL APPEARANCE  MANNER OF SPEAKING  PHYSICAL CONDITION  \
0                   4                   5                   4   
1                   4                   4                   4   
2                   4                   3                   3   
3                   3                   3                   3   
4                   4                   4                   3   

   MENTAL ALERTNESS  SELF-CONFIDENCE  ABILITY TO PRESENT IDEAS  \
0                 5                5                         5   
1                 4                4                         4   
2                 3                3                         3   
3                 2                3                         3   
4                 3                4                         4   

   COMMUNICATION SKILLS  Student Performance Rating  
0                     5                           5  
1                     3                           5  
2                     2                           5  
3                     3                           5  
4                     3                           5

### Distance calculation for creating adjacency matrix


In [10]:
from scipy.spatial.distance import cdist
s = cdist(u3, u3, 'cosine')
s

array([[0.00000000e+00, 1.18196406e-02, 3.89451766e-02, ...,
        5.70574961e-03, 1.75078592e-02, 1.18196406e-02],
       [1.18196406e-02, 0.00000000e+00, 1.07846501e-02, ...,
        6.69736532e-03, 3.57110435e-03, 7.69230769e-03],
       [3.89451766e-02, 1.07846501e-02, 0.00000000e+00, ...,
        2.63323597e-02, 1.15390226e-02, 2.00296533e-02],
       ...,
       [5.70574961e-03, 6.69736532e-03, 2.63323597e-02, ...,
        0.00000000e+00, 1.50356688e-02, 6.69736532e-03],
       [1.75078592e-02, 3.57110435e-03, 1.15390226e-02, ...,
        1.50356688e-02, 1.11022302e-16, 1.14792702e-02],
       [1.18196406e-02, 7.69230769e-03, 2.00296533e-02, ...,
        6.69736532e-03, 1.14792702e-02, 0.00000000e+00]])

In [11]:
X1=pd.DataFrame(s)
X1

0         1         2         3         4         5         6     \
0     0.000000  0.011820  0.038945  0.031784  0.015827  0.023852  0.023828   
1     0.011820  0.000000  0.010785  0.018050  0.006520  0.010005  0.017776   
2     0.038945  0.010785  0.000000  0.016536  0.011513  0.008478  0.038122   
3     0.031784  0.018050  0.016536  0.000000  0.011438  0.010986  0.043910   
4     0.015827  0.006520  0.011513  0.011438  0.000000  0.007125  0.027587   
...        ...       ...       ...       ...       ...       ...       ...   
2977  0.038945  0.010785  0.000000  0.016536  0.011513  0.008478  0.038122   
2978  0.005318  0.007692  0.029275  0.018050  0.014663  0.018689  0.026871   
2979  0.005706  0.006697  0.026332  0.030187  0.015583  0.013821  0.017178   
2980  0.017508  0.003571  0.011539  0.010289  0.003757  0.009008  0.018263   
2981  0.011820  0.007692  0.020030  0.018050  0.014663  0.010005  0.017776   

          7         8         9     ...      2972      2973      2974  \
0     0.036119  0.005732  0.010824  ...  0.055234  0.021551  0.015827   
1     0.017689  0.003403  0.011479  ...  0.039031  0.008924  0.006520   
2     0.009505  0.018376  0.021043  ...  0.021836  0.019694  0.011513   
3     0.031092  0.015332  0.020186  ...  0.030511  0.023098  0.021630   
4     0.021789  0.008436  0.012128  ...  0.034596  0.015815  0.008621   
...        ...       ...       ...  ...       ...       ...       ...   
2977  0.009505  0.018376  0.021043  ...  0.021836  0.019694  0.011513   
2978  0.034339  0.003403  0.011479  ...  0.048837  0.017695  0.014663   
2979  0.024151  0.004957  0.007793  ...  0.039112  0.020072  0.008125   
2980  0.024357  0.006251  0.016260  ...  0.042308  0.008163  0.012128   
2981  0.017689  0.003403  0.003571  ...  0.029225  0.017695  0.006520   

          2975      2976      2977      2978      2979          2980      2981  
0     0.022710  0.031191  0.038945  0.005318  0.005706  1.750786e-02  0.011820  
1     0.006520  0.018689  0.010785  0.007692  0.006697  3.571104e-03  0.007692  
2     0.011513  0.018915  0.000000  0.029275  0.026332  1.153902e-02  0.020030  
3     0.021630  0.043591  0.016536  0.018050  0.030187  1.028900e-02  0.018050  
4     0.017241  0.025511  0.011513  0.014663  0.015583  3.756706e-03  0.014663  
...        ...       ...       ...       ...       ...           ...       ...  
2977  0.011513  0.018915  0.000000  0.029275  0.026332  1.153902e-02  0.020030  
2978  0.014663  0.036057  0.029275  0.000000  0.006697  1.147927e-02  0.007692  
2979  0.008125  0.021774  0.026332  0.006697  0.000000  1.503567e-02  0.006697  
2980  0.012128  0.026863  0.011539  0.011479  0.015036  1.110223e-16  0.011479  
2981  0.006520  0.018689  0.020030  0.007692  0.006697  1.147927e-02  0.000000  

[2982 rows x 2982 columns]

In [12]:
# taking average of the hamming distance matrix
y = np.average(X1)
y

0.01856620671593297

In [13]:
adjmat_df=X1.copy()

In [14]:
# setting threshold value as mean of hamming matrix
adjmat_df[adjmat_df < y]=0
adjmat_df[adjmat_df >= y]=1

In [15]:
# adjacency matrix
adjmat_df

0     1     2     3     4     5     6     7     8     9     ...  2972  \
0      0.0   0.0   1.0   1.0   0.0   1.0   1.0   1.0   0.0   0.0  ...   1.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   1.0   
2      1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  ...   1.0   
3      1.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   1.0  ...   1.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0  ...   1.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2977   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  ...   1.0   
2978   0.0   0.0   1.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0  ...   1.0   
2979   0.0   0.0   1.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0  ...   1.0   
2980   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  ...   1.0   
2981   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   1.0   

      2973  2974  2975  2976  2977  2978  2979  2980  2981  
0      1.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
2      1.0   0.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0  
3      1.0   1.0   1.0   1.0   0.0   0.0   1.0   0.0   0.0  
4      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2977   1.0   0.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0  
2978   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  
2979   1.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  
2980   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
2981   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  

[2982 rows x 2982 columns]

In [16]:
G = nx.from_numpy_matrix(np.array(adjmat_df))
G

In [17]:
A=nx.to_numpy_matrix(G)
##Creating graph from adjacency matrix
H=nx.from_numpy_matrix(A)

### Construct a graph using stellargraph

In [18]:
square_feature_dataframe = StellarGraph.from_networkx(H, node_features=adjmat_df)
print(square_feature_dataframe.info())

StellarGraph: Undirected multigraph
 Nodes: 2982, Edges: 1793526

 Node types:
  default: [2982]
    Features: float32 vector, length 2982
    Edge types: default-default->default

 Edge types:
    default-default->default: [1793526]
        Weights: all 1 (default)
        Features: none


In [19]:
from stellargraph.mapper import (
    CorruptedGenerator,
    FullBatchNodeGenerator,
    GraphSAGENodeGenerator,
    HinSAGENodeGenerator,
    ClusterNodeGenerator,
)
from stellargraph import StellarGraph
from stellargraph.layer import GCN, DeepGraphInfomax, GraphSAGE, GAT, APPNP, HinSAGE
from stellargraph.mapper import ClusterNodeGenerator
from stellargraph import datasets
from stellargraph.utils import plot_history
from tensorflow.keras import layers, optimizers, losses, metrics, Model, regularizers
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.manifold import TSNE
from IPython.display import display, HTML

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
from tensorflow.keras import Model

### Node Generator

In [20]:
generator = FullBatchNodeGenerator(square_feature_dataframe, method="sgc", k=2)
generator 

Calculating 2-th power of normalized A...


In [21]:
target_encoding = preprocessing.LabelBinarizer()

targets = target_encoding.fit_transform(df['CLASS'])
targets

array([[1],
       [1],
       [0],
       ...,
       [1],
       [0],
       [1]])

In [22]:
targets.shape[1]

1

In [23]:
sgc = GCN(
    layer_sizes=[32],
    generator=generator,
    bias=True,
    dropout=0.5,
    activations=["softmax"],
    kernel_regularizer=regularizers.l2(5e-4),
)
sgc

In [24]:
# Expose the input and output tensors of the SGC model for node prediction,
# via GCN.in_out_tensors() method:
x_inp, predictions = sgc.in_out_tensors()

In [25]:
x_inp

[<KerasTensor: shape=(1, 2982, 2982) dtype=float32 (created by layer 'input_1')>,
 <KerasTensor: shape=(1, None) dtype=int32 (created by layer 'input_2')>,
 <KerasTensor: shape=(1, None, 2) dtype=int64 (created by layer 'input_3')>,
 <KerasTensor: shape=(1, None) dtype=float32 (created by layer 'input_4')>]

In [26]:
predictions

<KerasTensor: shape=(1, None, 32) dtype=float32 (created by layer 'gather_indices')>

In [27]:
model = Model(inputs=x_inp, outputs=predictions)

### Node embeddings

In [28]:
all_nodes = df['CLASS'].index
all_nodes

RangeIndex(start=0, stop=2982, step=1)

In [29]:
all_gen = generator.flow(all_nodes)
all_gen

In [30]:
emb = model.predict(all_gen)
emb.shape

1/1 [==============================] - 13s 13s/step


(1, 2982, 32)

In [31]:
emb

array([[[0.01075498, 0.07326806, 0.01827296, ..., 0.02527241,
         0.16005462, 0.02921717],
        [0.0185794 , 0.05266187, 0.02604709, ..., 0.02795803,
         0.0913531 , 0.02996253],
        [0.00691437, 0.09371731, 0.01473159, ..., 0.0331143 ,
         0.19508485, 0.02046376],
        ...,
        [0.01383245, 0.06486763, 0.02208682, ..., 0.02581411,
         0.13151748, 0.02959581],
        [0.0160966 , 0.05920114, 0.02520272, ..., 0.02913564,
         0.10489547, 0.02871341],
        [0.01578441, 0.05966878, 0.02499983, ..., 0.0288257 ,
         0.10807373, 0.02900045]]], dtype=float32)

In [32]:
w = emb.squeeze()

In [33]:
node_emb = pd.DataFrame(w)

In [34]:
y = df['CLASS']
y

0       1
1       1
2       0
3       0
4       1
       ..
2977    1
2978    1
2979    1
2980    0
2981    1
Name: CLASS, Length: 2982, dtype: int64

In [35]:
node_emb['Class']=y

In [36]:
node_emb

0         1         2         3         4         5         6  \
0     0.010755  0.073268  0.018273  0.025374  0.025352  0.029492  0.017128   
1     0.018579  0.052662  0.026047  0.028175  0.029471  0.027903  0.025231   
2     0.006914  0.093717  0.014732  0.022864  0.015884  0.018326  0.010752   
3     0.005487  0.101861  0.012623  0.021133  0.014502  0.018412  0.009112   
4     0.011803  0.074604  0.021505  0.025995  0.022311  0.023202  0.017506   
...        ...       ...       ...       ...       ...       ...       ...   
2977  0.006914  0.093717  0.014732  0.022864  0.015884  0.018326  0.010752   
2978  0.012977  0.065712  0.022206  0.026452  0.025981  0.027028  0.019878   
2979  0.013832  0.064868  0.022087  0.026884  0.027723  0.028307  0.020895   
2980  0.016097  0.059201  0.025203  0.027427  0.026781  0.025938  0.022768   
2981  0.015784  0.059669  0.025000  0.027152  0.027356  0.026468  0.022804   

             7         8         9  ...        23        24        25  \
0     0.035515  0.023285  0.030378  ...  0.016363  0.031817  0.026306   
1     0.035156  0.027667  0.031020  ...  0.023125  0.032134  0.026751   
2     0.027592  0.014610  0.022489  ...  0.014334  0.027072  0.025010   
3     0.026928  0.013325  0.021753  ...  0.012075  0.025755  0.024107   
4     0.032807  0.021103  0.027785  ...  0.018448  0.031377  0.026315   
...        ...       ...       ...  ...       ...       ...       ...   
2977  0.027592  0.014610  0.022489  ...  0.014334  0.027072  0.025010   
2978  0.035483  0.024289  0.030225  ...  0.019009  0.032072  0.025908   
2979  0.036101  0.025442  0.030999  ...  0.019111  0.032809  0.026114   
2980  0.034372  0.025357  0.030185  ...  0.021654  0.031904  0.026562   
2981  0.035239  0.025670  0.031022  ...  0.021230  0.032249  0.026518   

            26        27        28        29        30        31  Class  
0     0.009125  0.011999  0.036925  0.025272  0.160055  0.029217      1  
1     0.016940  0.018729  0.037662  0.027958  0.091353  0.029963      1  
2     0.009163  0.010163  0.037511  0.033114  0.195085  0.020464      0  
3     0.007184  0.008346  0.035291  0.030583  0.224320  0.020055      0  
4     0.013066  0.013911  0.036931  0.030852  0.137081  0.025667      1  
...        ...       ...       ...       ...       ...       ...    ...  
2977  0.009163  0.010163  0.037511  0.033114  0.195085  0.020464      1  
2978  0.012095  0.014059  0.037586  0.026344  0.135425  0.028726      1  
2979  0.011991  0.014379  0.037127  0.025814  0.131517  0.029596      1  
2980  0.015769  0.017023  0.037714  0.029136  0.104895  0.028713      0  
2981  0.015079  0.016484  0.037533  0.028826  0.108074  0.029000      1  

[2982 rows x 33 columns]

In [37]:
X=node_emb.drop(['Class'],axis=1)
Y=node_emb['Class']

In [38]:
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import classification_report,accuracy_score
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import metrics

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.metrics import confusion_matrix, recall_score, precision_score,f1_score
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [39]:
from sklearn.svm import LinearSVC
models = LinearSVC()
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    models.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(models.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.57981220657277
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1253
           1       0.58      1.00      0.73      1729

    accuracy                           0.58      2982
   macro avg       0.29      0.50      0.37      2982
weighted avg       0.34      0.58      0.43      2982

Confusion matrix:  [[   0 1253]
 [   0 1729]]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [40]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=10000) 
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lr.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lr.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.57981220657277
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1253
           1       0.58      1.00      0.73      1729

    accuracy                           0.58      2982
   macro avg       0.29      0.50      0.37      2982
weighted avg       0.34      0.58      0.43      2982

Confusion matrix:  [[   0 1253]
 [   0 1729]]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [41]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
rf = RandomForestClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    rf.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(rf.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9014084507042254
              precision    recall  f1-score   support

           0       0.90      0.87      0.88      1253
           1       0.91      0.93      0.92      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.90      0.90      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1086  167]
 [ 127 1602]]


In [42]:
gbc = GradientBoostingClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    gbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(gbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.8983903420523138
              precision    recall  f1-score   support

           0       0.90      0.86      0.88      1253
           1       0.90      0.93      0.91      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.89      0.90      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1076  177]
 [ 126 1603]]


In [43]:
import xgboost as xgb
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    xgbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(xgbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.8876592890677397
              precision    recall  f1-score   support

           0       0.88      0.85      0.86      1253
           1       0.89      0.91      0.90      1729

    accuracy                           0.89      2982
   macro avg       0.89      0.88      0.88      2982
weighted avg       0.89      0.89      0.89      2982

Confusion matrix:  [[1067  186]
 [ 149 1580]]


In [44]:
import lightgbm as lgb
lgb = lgb.LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=400, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lgb.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lgb.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.8725687458081824
              precision    recall  f1-score   support

           0       0.86      0.83      0.85      1253
           1       0.88      0.91      0.89      1729

    accuracy                           0.87      2982
   macro avg       0.87      0.87      0.87      2982
weighted avg       0.87      0.87      0.87      2982

Confusion matrix:  [[1036  217]
 [ 163 1566]]


In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=7, stratify=Y)

In [46]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
pa.fit(x_train, y_train)
y_pred=pa.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[220  31]
 [217 129]]
              precision    recall  f1-score   support

           0       0.50      0.88      0.64       251
           1       0.81      0.37      0.51       346

    accuracy                           0.58       597
   macro avg       0.65      0.62      0.57       597
weighted avg       0.68      0.58      0.56       597

accuracy_score:  0.5845896147403685


In [47]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
lsvm.fit(x_train, y_train)
y_pred=lsvm.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[  0 251]
 [  0 346]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       251
           1       0.58      1.00      0.73       346

    accuracy                           0.58       597
   macro avg       0.29      0.50      0.37       597
weighted avg       0.34      0.58      0.43       597

accuracy_score:  0.5795644891122278


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [48]:
rf = RandomForestClassifier(n_estimators=300)
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[217  34]
 [ 21 325]]
              precision    recall  f1-score   support

           0       0.91      0.86      0.89       251
           1       0.91      0.94      0.92       346

    accuracy                           0.91       597
   macro avg       0.91      0.90      0.90       597
weighted avg       0.91      0.91      0.91       597

accuracy_score:  0.9078726968174204


In [49]:
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
xgbc.fit(x_train, y_train)
y_pred=xgbc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[218  33]
 [ 29 317]]
              precision    recall  f1-score   support

           0       0.88      0.87      0.88       251
           1       0.91      0.92      0.91       346

    accuracy                           0.90       597
   macro avg       0.89      0.89      0.89       597
weighted avg       0.90      0.90      0.90       597

accuracy_score:  0.8961474036850922


In [50]:
log = LogisticRegression(max_iter=10000) 
log.fit(x_train, y_train)
y_pred=log.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[  0 251]
 [  0 346]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       251
           1       0.58      1.00      0.73       346

    accuracy                           0.58       597
   macro avg       0.29      0.50      0.37       597
weighted avg       0.34      0.58      0.43       597

accuracy_score:  0.5795644891122278


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
